# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: phongtro
    ports:
      - 3306:3306

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_PORT: 3306
      DB_HOST: db
    #   # DB_HOST: host.docker.internal
    ports:
     - 8000:8000
    expose:
     - 8000
    links:
      - db
 

  nginx:
    build: 
      context: .
    ports:
      - 80:80
    volumes:
      -  ../frontend/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

     #docker compose -p tmsky-nodejs-mysql up -d